site_name: React Dynamic Forms & Tables
site_description: A modern React library featuring JSON-based dynamic forms and tables with advanced configuration options
site_author: Your Name
site_url: https://yourusername.github.io/react-dynamic-forms-tables/

repo_name: yourusername/react-dynamic-forms-tables
repo_url: https://github.com/yourusername/react-dynamic-forms-tables
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - def_list
  - tables

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Components:
    - Dynamic Forms: dynamic-forms.md
    - Dynamic Tables: dynamic-tables.md
    - Permission System: permissions.md
  - API Reference: api-reference.md
  - Examples: examples.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername
    - icon: fontawesome/brands/npm
      link: https://www.npmjs.com/package/react-dynamic-forms-tables

extra_css:
  - assets/css/custom.css

extra_javascript:
  - assets/js/custom.js

copyright: Copyright &copy; 2023 Your Name
